libgit4cpp: git::Repository Class Reference
git::Repository Class Reference
Detailed Description
A class to wrap used methods from C-Library libgit2.
This class is necessary to handle C-pointers in a way that C++ programmers using this class do not have to think about them.
This class does not reflect the full libgit2 library. git functions which are not implemented in this class will be implemented in case of necessity
#include <Repository.h>
Public Member Functions
Repository (const std::filesystem::path &file_path)
Constructor which specifies the root dir of the git repository.
void reset_repo ()
Reset all knowledge this object knows about the repository and load the knowledge again.
std::filesystem::path get_path () const
Returns member variable, which is the root dir of the git repository.
git_repository * get_repo ()
Returns a non-owning raw pointer to the current repository.
void add (const std::string &glob="*")
Stage multiple new, changed, or removed files and folders in the repository directory.
void update (const std::string &glob="*")
Update the tracked files in the repository.
std::vector< int > add_files (const std::vector< std::filesystem::path > &filepaths)
Stage specific files listed in filepaths.
std::string get_last_commit_message ()
Return the commit message of the HEAD commit.
void commit (const std::string &commit_message)
Commit staged changes to the master branch of the git repository.
void reset (unsigned int nr_of_commits)
Hard reset of repository.
Remote add_remote (const std::string &remote_name, const std::string &url)
Add a new git remote with the specified name and URL to the repository.
gul14::optional< Remote > get_remote (const std::string &remote_name) const
Look up a git remote by name in the repository.
std::vector< Remote > list_remotes () const
Return a list of all configured remote repositories.
std::vector< std::string > list_remote_names () const
Return a list containing the names of all configured remote repositories (such as "origin").
void push (const Remote &remote, const std::string &refspec="HEAD:refs/heads/main")
Push something to the specified remote.
LibGitReference new_branch (const std::string &branch_name)
Create a new branch from the current branch.
LibGitReference new_branch (const std::string &branch_name, const std::string &origin_branch_name)
Create a new branch from a specified existing branch.
std::string get_current_branch_name ()
Returns the active branch in the repository.
std::vector< std::string > list_branches (BranchType type_flag=BranchType::all)
List the longnames of all branches.
void checkout (const std::string &branch_name, const std::vector< std::string > &paths={"*"})
Check out selected files from branch.
void switch_branch (const std::string &branch_name)
Switch branches by setting HEAD to an existing branch.
void remove_directory (const std::filesystem::path &directory)
Remove all entries from the index under a given directory.
void remove_files (const std::vector< std::filesystem::path > &filepaths)
Delete specific files from git index.
RepoState status ()
Returns current git status.
~Repository ()
Destructor.
Private Member Functions
void init (const std::filesystem::path &file_path)
Initialize a new git repository and commit all files in its path.
void commit_initial ()
Make the first commit.
LibGitCommit get_commit (unsigned int count=0)
Get a specific commit.
LibGitCommit get_commit (const std::string &ref)
Get a specific commit.
void make_signature ()
Load a git signature or create a default signature.
RepoState collect_status (LibGitStatusList &status) const
Translate all status information for each submodule into String.
Static Private Member Functions
static bool is_unstaged (FileStatus &filestats, const git_status_entry *s)
Check if the file from the status entry is not staged and collect the status in filestats.
static bool is_staged (FileStatus &filestats, const git_status_entry *s)
Check if the file from the status entry is not unstaged and collect the status in filestats.
Private Attributes
std::filesystem::path repo_path_
Path to the repository.
LibGitRepository repo_ { nullptr, git_repository_free }
Pointer which holds all infos of the active repository.
LibGitSignature my_signature_ { nullptr, git_signature_free }
Signature used in commits.
Constructor & Destructor Documentation
Repository()
git::Repository::Repository (const std::filesystem::path & file_path) explicit
Constructor which specifies the root dir of the git repository.
Parameters
file_path Path to git directory
References init().
~Repository()
git::Repository::~Repository ()
Destructor.
References my_signature_, and repo_.
Member Function Documentation
add()
void git::Repository::add (const std::string & glob = "*")
Stage multiple new, changed, or removed files and folders in the repository directory.
Instead of giving concrete paths to the files / objects to be added the function takes a shell like glob/wildcard:
* matches any number of any characters including none
? matches any single character
[abc] matches one character given in the bracket (abc is example)
[a-z] matches one character in the range of characters (a-z is example)
\* matches a star
\? matches a question mark
\\ matches a backslash
\[ matches an opening square bracket
The matching happens - unlike usual shells - on the whole pathname (inside the repository). So * matches all files (including all subdirectories).
Note: In fact you can never add a folder, you add files in a folder; i.e. it is impossible to add an empty folder. Git just knows files, not folders as items. If a file is in a folder the folder exists; if there is nothing in the folder the folder is ignored. (File means also links etc.)
Note: To write \? into a C++ string you probably need "\\?" etc.
Note: Globs do not match hidden files in the form of Unix dotfiles; to match them the pattern must explicitly start with . For example, * matches all visible files while .* matches all hidden files.
Parameters
glob The pattern with which files are selected to be added to the index
See also
add_files()
References repo_, and git::repository_index().
add_files()
std::vector< int > git::Repository::add_files (const std::vector< std::filesystem::path > & filepaths)
Stage specific files listed in filepaths.
Parameters
filepaths List of files. Either relative to repository root or absolute.
Returns
list of indices. An index from the filepaths vector is returned if the staging of the file failed. Returns an empty vector if all files were staged successfully.
See also
add()
References repo_, and git::repository_index().
add_remote()
Remote git::Repository::add_remote (const std::string & remote_name, const std::string & url)
Add a new git remote with the specified name and URL to the repository.
Returns
a Remote object representing the newly added remote
Exceptions
Error is thrown if the remote cannot be added, for instance because it already exists.
Repository repo{ "/path/to/repo" };
repo.add_remote("origin", "https://gitlab.com/a/b.git");
repo.add_remote("upstream", "file:///path/to/upstream/repo");
References git::remote, git::remote_create(), and repo_.
checkout()
void git::Repository::checkout (const std::string & branch_name, const std::vector< std::string > & paths = {"*"})
Check out selected files from branch.
The path parameter takes a list of files, directories. It supports pattern matching
Attention
GIT_FORCE flag is used. It may overwrite uncommitted changes in the current branch
Parameters
branch_name The branch to checkout
paths specifies the files to checkout
References get_commit(), git::parse_reference_from_name(), git::reference_name(), and repo_.
collect_status()
RepoState git::Repository::collect_status (LibGitStatusList & status) const private
Translate all status information for each submodule into String.
Parameters
status C-type status of all submodules from libgit
Returns
A vector of dynamic length which contains a status struct
References is_staged(), is_unstaged(), and status().
Referenced by status().
commit()
void git::Repository::commit (const std::string & commit_message)
Commit staged changes to the master branch of the git repository.
Parameters
commit_message Customized message for the commit
References get_commit(), my_signature_, repo_, git::repository_index(), and git::tree_lookup().
Referenced by get_commit(), get_last_commit_message(), and new_branch().
commit_initial()
void git::Repository::commit_initial () private
Make the first commit.
Function is called by init.
Note
slightly differs from commit because in this case, there is no previous commit to dock on.
References my_signature_, repo_, git::repository_index(), and git::tree_lookup().
Referenced by init().
get_commit() [1/2]
LibGitCommit git::Repository::get_commit (const std::string & ref) private
Get a specific commit.
Parameters
ref Use hex string identifier to find a commit
Returns
C-type commit object
References commit(), and repo_.
get_commit() [2/2]
LibGitCommit git::Repository::get_commit (unsigned int count = 0) private
Get a specific commit.
Parameters
count Jump back count number of commits behind HEAD
Returns
C-type commit object
Referenced by checkout(), commit(), get_last_commit_message(), new_branch(), and reset().
get_current_branch_name()
std::string git::Repository::get_current_branch_name ()
Returns the active branch in the repository.
Returns
shorthand name of current branch (eg. master)
References git::reference_shorthand(), repo_, and git::repository_head().
Referenced by new_branch().
get_last_commit_message()
std::string git::Repository::get_last_commit_message ()
Return the commit message of the HEAD commit.
Returns
message of last commit (=HEAD)
References commit(), and get_commit().
get_path()
std::filesystem::path git::Repository::get_path () const
Returns member variable, which is the root dir of the git repository.
References repo_path_.
get_remote()
gul14::optional< Remote > git::Repository::get_remote (const std::string & remote_name) const
Look up a git remote by name in the repository.
Returns
a Remote object if the remote exists, or an empty optional otherwise.
References git::remote, git::remote_lookup(), and repo_.
Referenced by list_remotes().
get_repo()
git_repository * git::Repository::get_repo ()
Returns a non-owning raw pointer to the current repository.
References repo_.
init()
void git::Repository::init (const std::filesystem::path & file_path) private
Initialize a new git repository and commit all files in its path.
Note
This is a private member function because git repository init should be done by an LibGit Object Initialization
References commit_initial(), make_signature(), repo_, repo_path_, git::repository_init(), git::repository_open(), and update().
Referenced by Repository(), and reset_repo().
is_staged()
bool git::Repository::is_staged (FileStatus & filestats, const git_status_entry * s) static private
Check if the file from the status entry is not unstaged and collect the status in filestats.
Note
this function is solely called by collect_status. It has no other purpose.
Parameters
filestats a structure which will be filled with the status of the file if the file is staged
s status of the file. A struct which contains flags about every possible state
Returns
true if file is staged (and filestats initialized), else false
References git::FileStatus::changes, git::FileStatus::handling, and git::FileStatus::path_name.
Referenced by collect_status().
is_unstaged()
bool git::Repository::is_unstaged (FileStatus & filestats, const git_status_entry * s) static private
Check if the file from the status entry is not staged and collect the status in filestats.
Note
this function is solely called by collect_status. It has no other purpose.
Parameters
filestats a structure which will be filled with the status of the file if the file is unstaged
s status of the file. A struct which contains flags about every possible state
Returns
true if file is unstaged (and filestats initialized), else false
References git::FileStatus::changes, git::FileStatus::handling, and git::FileStatus::path_name.
Referenced by collect_status().
list_branches()
std::vector< std::string > git::Repository::list_branches (BranchType type_flag = BranchType::all)
List the longnames of all branches.
Parameters
type_flag defines which types of branches should be listed
Returns
vector of branch longnames
References git::all, git::branch_iterator(), git::branch_next(), git::local, git::reference_name(), git::remote, and repo_.
list_remote_names()
std::vector< std::string > git::Repository::list_remote_names () const
Return a list containing the names of all configured remote repositories (such as "origin").
Exceptions
Error is thrown if the remote list cannot be retrieved.
References repo_.
Referenced by list_remotes().
list_remotes()
std::vector< Remote > git::Repository::list_remotes () const
Return a list of all configured remote repositories.
Exceptions
Error is thrown if the list cannot be retrieved.
References get_remote(), and list_remote_names().
make_signature()
void git::Repository::make_signature () private
Load a git signature or create a default signature.
References my_signature_, repo_, git::signature_default(), and git::signature_new().
Referenced by init().
new_branch() [1/2]
LibGitReference git::Repository::new_branch (const std::string & branch_name)
Create a new branch from the current branch.
Parameters
branch_name name of the new branch
References get_current_branch_name().
new_branch() [2/2]
LibGitReference git::Repository::new_branch (const std::string & branch_name, const std::string & origin_branch_name)
Create a new branch from a specified existing branch.
Parameters
branch_name name of the new branch
origin_branch_name name of the existing branch to checkout from
Returns
The reference object of the new branch
References git::branch_create(), git::branch_lookup(), commit(), get_commit(), git::reference_name(), and repo_.
push()
void git::Repository::push (const Remote & remote, const std::string & refspec = "HEAD:refs/heads/main")
Push something to the specified remote.
In git parlance, this updates a remote ref from a local ref. The "refspec" specifies which local ref and which remote ref is used. For instance, the default "HEAD:refs/heads/main" pushes HEAD (whatever is currently checked out in the local working directory) to the remote branch "main".
Parameters
remote The git remote to push to (e.g. obtained by get_remote())
refspec The refspec to push (e.g. "HEAD" or "refs/heads/main")
References git::get_dummy_credentials_callback(), and git::remote.
remove_directory()
void git::Repository::remove_directory (const std::filesystem::path & directory)
Remove all entries from the index under a given directory.
No files are removed from the filesystem.
Parameters
directory Directory to remove
Attention
Directory is a relative path within repo_path_ \See remove_files() for hints about file removal
References repo_, and git::repository_index().
remove_files()
void git::Repository::remove_files (const std::vector< std::filesystem::path > & filepaths)
Delete specific files from git index.
No files are removed from the filesystem.
They also do not need to exist on the filesystem to be removable from the index.
To delete files from the repository you can eiter:
remove the files from the repository With remove_files()
and remove the files from the filesystem with std::filesystem::remove()
remove the files from the filesystem with std::filesystem::remove()
add the removal of the files with add_files() or with remove_files()
Parameters
filepaths list of files
Attention
files in filepaths are relative to repo_path_
See also
remove_directory()
References repo_, and git::repository_index().
reset()
void git::Repository::reset (unsigned int nr_of_commits)
Hard reset of repository.
Parameters
nr_of_commits number of commits to jump back
References get_commit(), and repo_.
Referenced by switch_branch().
reset_repo()
void git::Repository::reset_repo ()
Reset all knowledge this object knows about the repository and load the knowledge again.
References init(), my_signature_, repo_, and repo_path_.
status()
RepoState git::Repository::status ()
Returns current git status.
This includes unchanged, untracked and ingnored files and directories. Each files status is represented by – file name – change status (has the file changed) – handling status (what git will do with it)
Returns
vector of file status for each file.
References collect_status(), repo_, and git::status_list_new().
Referenced by collect_status().
switch_branch()
void git::Repository::switch_branch (const std::string & branch_name)
Switch branches by setting HEAD to an existing branch.
Attention
If the branch doesn't exist yet, no error will be thrown. The HEAD will then be attached to an unborn branch.
Parameters
branch_name ID, shorthand or full reference name of branch
References git::parse_reference_from_name(), git::reference_name(), repo_, and reset().
update()
void git::Repository::update (const std::string & glob = "*")
Update the tracked files in the repository.
The same as add() but only considers files that are already in the repository, never adding just updating.
Parameters
glob The pattern with which files are selected to be added to the index
See also
add() for an explanantion on the glob.
References repo_, and git::repository_index().
Referenced by init().
Member Data Documentation
my_signature_
LibGitSignature git::Repository::my_signature_ { nullptr, git_signature_free } private
Signature used in commits.
Referenced by commit(), commit_initial(), make_signature(), reset_repo(), and ~Repository().
repo_
LibGitRepository git::Repository::repo_ { nullptr, git_repository_free } private
Pointer which holds all infos of the active repository.
Referenced by add(), add_files(), add_remote(), checkout(), commit(), commit_initial(), get_commit(), get_current_branch_name(), get_remote(), get_repo(), init(), list_branches(), list_remote_names(), make_signature(), new_branch(), remove_directory(), remove_files(), reset(), reset_repo(), status(), switch_branch(), update(), and ~Repository().
repo_path_
std::filesystem::path git::Repository::repo_path_ private
Path to the repository.
Referenced by get_path(), init(), and reset_repo().
The documentation for this class was generated from the following files:
Repository.h
Repository.cc