libgit4cpp: git::Remote Class Reference
git::Remote Class Reference
Detailed Description
An abstraction of a git remote repository (such as "origin").
A remote has a name and a URL which can be accessed via get_name() and get_url(), respectively. In addition, a non-owning pointer to the underlying git_remote object can be retrieved via get().
#include <Remote.h>
Public Member Functions
Remote (LibGitRemote &&remote_ptr)
Construct a Remote object by taking the ownership of a git_remote unique pointer.
git_remote * get () const
Return a non-owning pointer to the underlying git remote object.
std::string get_name () const
Return the name of the remote (e.g. "origin"). May be empty for in-memory remotes.
std::string get_url () const
Return the URL of the remote (e.g. "https://gitlab.com/a/b.git").
std::vector< std::string > list_references ()
Retrieve a list of references available on this remote repository ("git ls-remote").
Private Attributes
LibGitRemote remote_ { nullptr, git_remote_free }
Constructor & Destructor Documentation
Remote()
git::Remote::Remote (LibGitRemote && remote_ptr)
Construct a Remote object by taking the ownership of a git_remote unique pointer.
The constructor queries the name and URL of the remote and caches them for later access via get_name() and get_url().
Exceptions
Error is thrown if the given pointer is null.
References remote_.
Member Function Documentation
get()
git_remote* git::Remote::get () const inline
Return a non-owning pointer to the underlying git remote object.
References remote_.
Referenced by git::GitRepository::push().
get_name()
std::string git::Remote::get_name () const
Return the name of the remote (e.g. "origin"). May be empty for in-memory remotes.
References remote_.
Referenced by list_references().
get_url()
std::string git::Remote::get_url () const
Return the URL of the remote (e.g. "https://gitlab.com/a/b.git").
References remote_.
list_references()
std::vector< std::string > git::Remote::list_references ()
Retrieve a list of references available on this remote repository ("git ls-remote").
Note
The API for this function is preliminary. It would be more useful to return not just the names of the references, but also additional details like the commit IDs.
References git::get_dummy_credentials_callback(), get_name(), and remote_.
Member Data Documentation
remote_
LibGitRemote git::Remote::remote_ { nullptr, git_remote_free } private
Referenced by get(), get_name(), get_url(), list_references(), and Remote().
The documentation for this class was generated from the following files:
Remote.h
Remote.cc