libgit4cpp: git::GitRepository Class Reference
git::GitRepository Class Reference
Detailed Description
A class to wrap used methods from C-Library libgit2.
This class is necessary to handle C-pointers in a way that C++ programmers using this class do not have to think about them.
This class does not reflect the full libgit2 library. git functions which are not implemented in this class will be implemented in case of necessity
#include <GitRepository.h>
Public Member Functions
GitRepository (const std::filesystem::path &file_path, const std::string &url={ })
Constructor which specifies the root dir of the git repository.
void reset_repo ()
Reset all knowledge this object knows about the repository and load the knowledge again.
std::filesystem::path get_path () const
Returns member variable, which is the root dir of the git repository.
git_repository * get_repo ()
Returns a non-owning raw pointer to the current repository.
void add (const std::string &glob="*")
Stage multiple new, changed, or removed files and folders in the repository directory.
void update (const std::string &glob="*")
Update the tracked files in the repository.
std::vector< int > add_files (const std::vector< std::filesystem::path > &filepaths)
Stage specific files listed in filepaths.
std::string get_last_commit_message ()
Return the commit message of the HEAD commit.
void commit (const std::string &commit_message)
Commit staged changes to the master branch of the git repository.
void reset (unsigned int nr_of_commits)
Hard reset of repository.
void push ()
Push commits to the repository.
void pull ()
Pull changes from the remote repository.
void clone_repo (const std::string &url, const std::filesystem::path &repo_path)
Clone a repository.
bool branch_up_to_date (const std::string &branch_name)
Check if remote and local branch are in same state.
void remove_directory (const std::filesystem::path &directory)
Remove all entries from the index under a given directory.
void remove_files (const std::vector< std::filesystem::path > &filepaths)
Delete specific files from git index.
RepoState status ()
Returns current git status.
~GitRepository ()
Destructor.
Private Member Functions
void init (const std::filesystem::path &file_path)
Initialize a new git repository and commit all files in its path.
void commit_initial ()
Make the first commit.
LibGitPointer< git_commit > get_commit (unsigned int count=0)
Get a specific commit.
LibGitPointer< git_commit > get_commit (const std::string &ref)
Get a specific commit.
void make_signature ()
Load a git signature or create a default signature.
RepoState collect_status (LibGitPointer< git_status_list > &status) const
Translate all status information for each submodule into String.
void construct (const std::filesystem::path &file_path)
Basic construction code, extracted because of constructor overload.
Static Private Member Functions
static bool is_unstaged (FileStatus &filestats, const git_status_entry *s)
Check if the file from the status entry is not staged and collect the status in filestats.
static bool is_staged (FileStatus &filestats, const git_status_entry *s)
Check if the file from the status entry is not unstaged and collect the status in filestats.
Private Attributes
std::filesystem::path repo_path_
Path to the repository.
std::string url_
URL of the remote repository.
LibGitPointer< git_remote > remote_ { }
git remote object
LibGitPointer< git_repository > repo_ { }
Pointer which holds all infos of the active repository.
LibGitPointer< git_signature > my_signature_
Signature used in commits.
Constructor & Destructor Documentation
GitRepository()
git::GitRepository::GitRepository (const std::filesystem::path & file_path, const std::string & url = { }) explicit
Constructor which specifies the root dir of the git repository.
Parameters
file_path Path to git directory
url Optional remote repository url
References git::LibGitPointer< T >::get(), init(), remote_, git::remote_create(), git::remote_lookup(), and repo_.
~GitRepository()
git::GitRepository::~GitRepository ()
Destructor.
References my_signature_, repo_, and git::LibGitPointer< T >::reset().
Member Function Documentation
add()
void git::GitRepository::add (const std::string & glob = "*")
Stage multiple new, changed, or removed files and folders in the repository directory.
Instead of giving concrete paths to the files / objects to be added the function takes a shell like glob/wildcard:
* matches any number of any characters including none
? matches any single character
[abc] matches one character given in the bracket (abc is example)
[a-z] matches one character in the range of characters (a-z is example)
\* matches a star
\? matches a question mark
\\ matches a backslash
\[ matches an opening square bracket
The matching happens - unlike usual shells - on the whole pathname (inside the repository). So * matches all files (including all subdirectories).
Note: In fact you can never add a folder, you add files in a folder; i.e. it is impossible to add an empty folder. Git just knows files, not folders as items. If a file is in a folder the folder exists; if there is nothing in the folder the folder is ignored. (File means also links etc.)
Note: To write \? into a C++ string you probably need "\\?" etc.
Note: Globs do not match hidden files in the form of Unix dotfiles; to match them the pattern must explicitly start with . For example, * matches all visible files while .* matches all hidden files.
Parameters
glob The pattern with which files are selected to be added to the index
See also
add_files()
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
add_files()
std::vector< int > git::GitRepository::add_files (const std::vector< std::filesystem::path > & filepaths)
Stage specific files listed in filepaths.
Parameters
filepaths List of files. Either relative to repository root or absolute.
Returns
list of indices. An index from the filepaths vector is returned if the staging of the file failed. Returns an empty vector if all files were staged successfully.
See also
add()
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
branch_up_to_date()
bool git::GitRepository::branch_up_to_date (const std::string & branch_name)
Check if remote and local branch are in same state.
Parameters
branch_name
References git::branch_lookup(), git::branch_remote_name(), git::LibGitPointer< T >::get(), git::remote_lookup(), and repo_.
clone_repo()
void git::GitRepository::clone_repo (const std::string & url, const std::filesystem::path & repo_path)
Clone a repository.
Parameters
addr Address of the git repository host
References git::clone(), git::LibGitPointer< T >::get(), remote_, git::remote_lookup(), repo_, repo_path_, and url_.
collect_status()
RepoState git::GitRepository::collect_status (LibGitPointer< git_status_list > & status) const private
Translate all status information for each submodule into String.
Parameters
status C-type status of all submodules from libgit
Returns
A vector of dynamic length which contains a status struct
References is_staged(), is_unstaged(), and status().
Referenced by status().
commit()
void git::GitRepository::commit (const std::string & commit_message)
Commit staged changes to the master branch of the git repository.
Parameters
commit_message Customized message for the commit
References git::LibGitPointer< T >::get(), get_commit(), my_signature_, repo_, git::repository_index(), and git::tree_lookup().
Referenced by get_commit(), and get_last_commit_message().
commit_initial()
void git::GitRepository::commit_initial () private
Make the first commit.
Function is called by init.
Note
slightly differs from commit because in this case, there is no previous commit to dock on.
References git::LibGitPointer< T >::get(), my_signature_, repo_, git::repository_index(), and git::tree_lookup().
Referenced by init().
construct()
void git::GitRepository::construct (const std::filesystem::path & file_path) private
Basic construction code, extracted because of constructor overload.
Parameters
file_path path to the repository
get_commit() [1/2]
LibGitPointer< git_commit > git::GitRepository::get_commit (const std::string & ref) private
Get a specific commit.
Parameters
ref Use hex string identifier to find a commit
Returns
C-type commit object
References commit(), git::LibGitPointer< T >::get(), and repo_.
get_commit() [2/2]
LibGitPointer< git_commit > git::GitRepository::get_commit (unsigned int count = 0) private
Get a specific commit.
Parameters
count Jump back count number of commits behind HEAD
Returns
C-type commit object
Referenced by commit(), get_last_commit_message(), and reset().
get_last_commit_message()
std::string git::GitRepository::get_last_commit_message ()
Return the commit message of the HEAD commit.
Returns
message of last commit (=HEAD)
References commit(), and get_commit().
get_path()
std::filesystem::path git::GitRepository::get_path () const
Returns member variable, which is the root dir of the git repository.
References repo_path_.
get_repo()
git_repository * git::GitRepository::get_repo ()
Returns a non-owning raw pointer to the current repository.
References git::LibGitPointer< T >::get(), and repo_.
init()
void git::GitRepository::init (const std::filesystem::path & file_path) private
Initialize a new git repository and commit all files in its path.
Note
This is a private member function because git repository init should be done by an LibGit Object Initialization
References commit_initial(), git::LibGitPointer< T >::get(), make_signature(), repo_, repo_path_, git::repository_init(), git::repository_open(), and update().
Referenced by GitRepository(), and reset_repo().
is_staged()
bool git::GitRepository::is_staged (FileStatus & filestats, const git_status_entry * s) static private
Check if the file from the status entry is not unstaged and collect the status in filestats.
Note
this function is solely called by collect_status. It has no other purpose.
Parameters
filestats a structure which will be filled with the status of the file if the file is staged
s status of the file. A struct which contains flags about every possible state
Returns
true if file is staged (and filestats initialized), else false
References git::FileStatus::changes, git::FileStatus::handling, and git::FileStatus::path_name.
Referenced by collect_status().
is_unstaged()
bool git::GitRepository::is_unstaged (FileStatus & filestats, const git_status_entry * s) static private
Check if the file from the status entry is not staged and collect the status in filestats.
Note
this function is solely called by collect_status. It has no other purpose.
Parameters
filestats a structure which will be filled with the status of the file if the file is unstaged
s status of the file. A struct which contains flags about every possible state
Returns
true if file is unstaged (and filestats initialized), else false
References git::FileStatus::changes, git::FileStatus::handling, and git::FileStatus::path_name.
Referenced by collect_status().
make_signature()
void git::GitRepository::make_signature () private
Load a git signature or create a default signature.
References git::LibGitPointer< T >::get(), my_signature_, repo_, git::signature_default(), and git::signature_new().
Referenced by init().
pull()
void git::GitRepository::pull ()
Pull changes from the remote repository.
Parameters
addr Address of the git repository host
References git::LibGitPointer< T >::get(), remote_, and repo_.
push()
void git::GitRepository::push ()
Push commits to the repository.
Parameters
addr Address of the remote git repository host
References git::LibGitPointer< T >::get(), and remote_.
remove_directory()
void git::GitRepository::remove_directory (const std::filesystem::path & directory)
Remove all entries from the index under a given directory.
No files are removed from the filesystem.
Parameters
directory Directory to remove
Attention
Directory is a relative path within repo_path_ \See remove_files() for hints about file removal
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
remove_files()
void git::GitRepository::remove_files (const std::vector< std::filesystem::path > & filepaths)
Delete specific files from git index.
No files are removed from the filesystem.
They also do not need to exist on the filesystem to be removable from the index.
To delete files from the repository you can eiter:
remove the files from the repository With remove_files()
and remove the files from the filesystem with std::filesystem::remove()
remove the files from the filesystem with std::filesystem::remove()
add the removal of the files with add_files() or with remove_files()
Parameters
filepaths list of files
Attention
files in filepaths are relative to repo_path_
See also
remove_directory()
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
reset()
void git::GitRepository::reset (unsigned int nr_of_commits)
Hard reset of repository.
Parameters
nr_of_commits number of commits to jump back
References git::LibGitPointer< T >::get(), get_commit(), and repo_.
reset_repo()
void git::GitRepository::reset_repo ()
Reset all knowledge this object knows about the repository and load the knowledge again.
References init(), my_signature_, repo_, repo_path_, and git::LibGitPointer< T >::reset().
status()
RepoState git::GitRepository::status ()
Returns current git status.
This includes unchanged, untracked and ingnored files and directories. Each files status is represented by – file name – change status (has the file changed) – handling status (what git will do with it)
Returns
vector of file status for each file.
References collect_status(), git::LibGitPointer< T >::get(), repo_, and git::status_list_new().
Referenced by collect_status().
update()
void git::GitRepository::update (const std::string & glob = "*")
Update the tracked files in the repository.
The same as add() but only considers files that are already in the repository, never adding just updating.
Parameters
glob The pattern with which files are selected to be added to the index
See also
add() for an explanantion on the glob.
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
Referenced by init().
Member Data Documentation
my_signature_
LibGitPointer<git_signature> git::GitRepository::my_signature_ private
Signature used in commits.
Referenced by commit(), commit_initial(), make_signature(), reset_repo(), and ~GitRepository().
remote_
LibGitPointer<git_remote> git::GitRepository::remote_ { } private
git remote object
Referenced by clone_repo(), GitRepository(), pull(), and push().
repo_
LibGitPointer<git_repository> git::GitRepository::repo_ { } private
Pointer which holds all infos of the active repository.
Referenced by add(), add_files(), branch_up_to_date(), clone_repo(), commit(), commit_initial(), get_commit(), get_repo(), GitRepository(), init(), make_signature(), pull(), remove_directory(), remove_files(), reset(), reset_repo(), status(), update(), and ~GitRepository().
repo_path_
std::filesystem::path git::GitRepository::repo_path_ private
Path to the repository.
Referenced by clone_repo(), get_path(), init(), and reset_repo().
url_
std::string git::GitRepository::url_ private
URL of the remote repository.
Referenced by clone_repo().
The documentation for this class was generated from the following files:
GitRepository.h
GitRepository.cc