libgit4cpp: Group of wrapped libgit2 functions
Group of wrapped libgit2 functions
Detailed Description
Function wrappers for libgit2 functions which manipulate pointers.
(Which take double pointers as parameters)
Note
for documentation see the associated libgit2 function name: "git_FUNCTIONNAME"
Functions
LibGitPointer< git_repository > git::repository_open (const std::string &repo_path)
Return an existing repository.
LibGitPointer< git_repository > git::repository_init (const std::string &repo_path, bool is_bare)
Return a fresh initialized repository.
LibGitPointer< git_index > git::repository_index (git_repository *repo)
Return the current index of a repository.
LibGitPointer< git_signature > git::signature_default (git_repository *repo)
Generate a signature from system values (already collected by the C-type repository).
LibGitPointer< git_signature > git::signature_new (const std::string &name, const std::string &email, time_t time, int offset)
Generate a signature from given parameters.
LibGitPointer< git_tree > git::tree_lookup (git_repository *repo, git_oid tree_id)
Collect the current tree of the git repository.
LibGitPointer< git_status_list > git::status_list_new (git_repository *repo, const git_status_options &status_opt)
Create a new status list which contains status_list_entry* elements.
LibGitPointer< git_reference > git::repository_head (git_repository *repo)
Collect the reference to the repository head.
LibGitPointer< git_remote > git::remote_create (git_repository *repo, const std::string &remote_name, const std::string &url)
Create a new remote connection in the repository and returns it.
LibGitPointer< git_remote > git::remote_lookup (git_repository *repo, const std::string &remote_name)
Collects the remove connection by name and returns it.
LibGitPointer< git_repository > git::clone (const std::string &url, const std::string &repo_path)
Clone existing git repository into local filesystem.
LibGitPointer< git_reference > git::branch_lookup (git_repository *repo, const std::string &branch_name, git_branch_t branch_type)
Find the reference to a branch where the name is known.
std::string git::branch_remote_name (git_repository *repo, const std::string &branch_name)
Return the name of a remote name.
Function Documentation
branch_lookup()
LibGitPointer< git_reference > git::branch_lookup (git_repository * repo, const std::string & branch_name, git_branch_t branch_type)
Find the reference to a branch where the name is known.
Parameters
repo C-type repository
branch_name e.g. 'master', '3_fix bugs', etc...
branch_type enum with 1=GIT_BRANCH_LOCAL, 2=GIT_BRANCH_REMOTE, 3=GIT_BRANCH_ALL
Returns
Wrapper of git reference
Referenced by git::GitRepository::branch_up_to_date().
branch_remote_name()
std::string git::branch_remote_name (git_repository * repo, const std::string & branch_name)
Return the name of a remote name.
Parameters
repo C-type repository
branch_name e.g. 'master', '3_fix bugs', etc...
Returns
remote name, typically 'origin/master' or 'origin/3_fix_bugs'
Referenced by git::GitRepository::branch_up_to_date().
clone()
LibGitPointer< git_repository > git::clone (const std::string & url, const std::string & repo_path)
Clone existing git repository into local filesystem.
Parameters
url adress of remote connection, e.g https://github.com/...
repo_path absolute or relative path from executable
Returns
Wrapper of a repository
Referenced by git::GitRepository::clone_repo().
remote_create()
LibGitPointer< git_remote > git::remote_create (git_repository * repo, const std::string & remote_name, const std::string & url)
Create a new remote connection in the repository and returns it.
Parameters
repo C-type repository
remote_name typically 'origin'
url adress of remote connection, e.g https://github.com/...
Returns
Wrapper of a remote connection
Referenced by git::GitRepository::GitRepository().
remote_lookup()
LibGitPointer< git_remote > git::remote_lookup (git_repository * repo, const std::string & remote_name)
Collects the remove connection by name and returns it.
Parameters
repo C-type repository
remote_name typically 'origin'
Returns
Wrapper of a remote connection
Referenced by git::GitRepository::branch_up_to_date(), git::GitRepository::clone_repo(), and git::GitRepository::GitRepository().
repository_head()
LibGitPointer< git_reference > git::repository_head (git_repository * repo)
Collect the reference to the repository head.
Parameters
repo C-type repository
Returns
Wrapper of git_reference*
repository_index()
LibGitPointer< git_index > git::repository_index (git_repository * repo)
Return the current index of a repository.
Parameters
repo C-type repository
Returns
Wrapper of a git_index*
Referenced by git::GitRepository::add(), git::GitRepository::add_files(), git::GitRepository::commit(), git::GitRepository::commit_initial(), git::GitRepository::remove_directory(), git::GitRepository::remove_files(), and git::GitRepository::update().
repository_init()
LibGitPointer< git_repository > git::repository_init (const std::string & repo_path, bool is_bare)
Return a fresh initialized repository.
Parameters
repo_path absolute or relative path from executable
is_bare if true, a git repo is created at repo_path. Else, .git is created in repo_path.
Returns
Wrapper of a git_repository*
Referenced by git::GitRepository::init().
repository_open()
LibGitPointer< git_repository > git::repository_open (const std::string & repo_path)
Return an existing repository.
Parameters
repo_path absolute or relative path from executable
Returns
Wrapper of a git_repository*
Referenced by git::GitRepository::init().
signature_default()
LibGitPointer< git_signature > git::signature_default (git_repository * repo)
Generate a signature from system values (already collected by the C-type repository).
Parameters
repo_path absolute or relative path from executable
Returns
Wrapper of a git_signature*
Referenced by git::GitRepository::make_signature().
signature_new()
LibGitPointer< git_signature > git::signature_new (const std::string & name, const std::string & email, time_t time, int offset)
Generate a signature from given parameters.
Parameters
name User name who creates the commit
email E-mail of the user
time timestamp
offset timezone adjustment for the timezone
Returns
Wrapper of a git_signature*
Referenced by git::GitRepository::make_signature().
status_list_new()
LibGitPointer< git_status_list > git::status_list_new (git_repository * repo, const git_status_options & status_opt)
Create a new status list which contains status_list_entry* elements.
Parameters
repo C-type repository
status_opt struct of status options
Returns
Wrapper of git_status_list*
Referenced by git::GitRepository::status().
tree_lookup()
LibGitPointer< git_tree > git::tree_lookup (git_repository * repo, git_oid tree_id)
Collect the current tree of the git repository.
Parameters
repo C-type repository
tree_id identity number of the active tree
Returns
Wrapper of a git_signature*
Referenced by git::GitRepository::commit(), and git::GitRepository::commit_initial().